
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 05 15:13:26 CEST 2025
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DISTINTO = 5;
  public static final int FUNCTION = 28;
  public static final int PARENTESISCIERRE = 9;
  public static final int MULT = 2;
  public static final int ENTERO = 15;
  public static final int INTEGER = 31;
  public static final int OUT = 36;
  public static final int MINUS = 3;
  public static final int DELIMTIPO = 14;
  public static final int IDENTIFICADOR = 18;
  public static final int IS = 29;
  public static final int AND = 20;
  public static final int IDERR = 38;
  public static final int RECORD = 27;
  public static final int TYPE = 37;
  public static final int BEGIN = 34;
  public static final int PARENTESISAP = 8;
  public static final int LOOP = 35;
  public static final int IF = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int RETURN = 24;
  public static final int error = 1;
  public static final int CONSTANT = 19;
  public static final int ASIGNACION = 6;
  public static final int PUTLINE = 21;
  public static final int MAYOR = 4;
  public static final int DELIMCOMENTARIO = 10;
  public static final int ELSE = 23;
  public static final int CADENACARACTERES = 17;
  public static final int WHILE = 22;
  public static final int ACCESO = 7;
  public static final int THEN = 30;
  public static final int DELIMLISTA = 12;
  public static final int END = 33;
  public static final int BOOLEANO = 16;
  public static final int DELIMCADENA = 11;
  public static final int PROCEDURE = 26;
  public static final int DELIMPUNTOCOMA = 13;
}

